run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  disable-all: true
  enable:
    # Critical bug detection
    - govet
    - staticcheck
    - bodyclose
    - nilerr
    - sqlclosecheck
    - errcheck

    # Security
    - gosec

    # Code quality
    - gocritic
    - revive
    - gocyclo

    # Basic formatting
    - gofmt
    - goimports

    # Unused code
    - unused
    - ineffassign

    # Imports
    - depguard

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use log/slog instead"
          - pkg: "github.com/rs/zerolog"
            desc: "use log/slog instead"
          - pkg: "github.com/pkg/errors"
            desc: "use fmt.Errorf with %w instead"
          - pkg: "io/ioutil"
            desc: "deprecated, use io and os packages"

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - ifElseChain  # Sometimes if-else chains are more readable

  revive:
    rules:
      - name: unused-parameter
        severity: warning
      - name: redefines-builtin-id
        severity: error

issues:
  exclude-rules:
    # Test files - only exclude specific linters that don't apply
    - path: _test\.go
      linters:
        - errcheck     # Test code often intentionally ignores errors
        - gosec        # Test code may use insecure patterns intentionally
        - gocyclo      # Test functions can be complex

    # Test utilities
    - path: internal/testutil/
      linters:
        - errcheck
        - gosec
        - revive

    # Validation experiments
    - path: internal/validation/
      linters:
        - errcheck
        - gosec
        - revive
        - gocritic

    # Generated files
    - path: ".*_gen\\.go"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
