run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  disable-all: true
  enable:
    # Critical bug detection only
    - govet
    - staticcheck
    - bodyclose
    - nilerr
    - sqlclosecheck

    # Basic formatting
    - gofmt
    - goimports

    # Unused code
    - unused
    - ineffassign

    # Imports
    - depguard

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use log/slog instead"
          - pkg: "github.com/rs/zerolog"
            desc: "use log/slog instead"
          - pkg: "github.com/pkg/errors"
            desc: "use fmt.Errorf with %w instead"
          - pkg: "io/ioutil"
            desc: "deprecated, use io and os packages"

issues:
  exclude-rules:
    # Test files
    - path: _test\.go
      linters:
        - all

    # Test utilities
    - path: internal/testutil/
      linters:
        - all

    # Validation experiments
    - path: internal/validation/
      linters:
        - all

    # Generated files
    - path: ".*_gen\\.go"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
