name: Question
description: Ask a question about usage or behavior
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for your question. Provide details so we can help quickly.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant background, commands, or configuration.
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "v0.1.0"
    validations:
      required: true
